[features]
resolution = true
skip-lint = false

[programs.localnet]
unikron = "7saCDPbxRTGEPeyTYZgXyzNVr5LXFPEnYKpVyAqT2QNd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/unikron"]

[scripts]
test = "mocha -r ts-node/register -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.31.1"

[test]
script = "mocha -r ts-node/register -t 1000000 tests/**/*.ts"
